version: '3.8'

services:
  sistema.fluxo.caixa.database:
    container_name: sistema_fluxo_caixa_database
    image: postgres:15-alpine

    environment:
      POSTGRES_DB: fluxo_caixa
      POSTGRES_USER: root
      POSTGRES_PASSWORD: fintech@0152
    ports:
      - "5432:5432"
    restart: unless-stopped


  sistema.fluxo.caixa.cache:
    container_name: sistema_fluxo_caixa_cache 
    image: redis:7.4.1-alpine     
    command: redis-server --requirepass fintech@0152
    environment:
       MONGO_INITDB_ROOT_USERNAME: developer
       MONGO_INITDB_ROOT_PASSWORD:  fintech@0152
    ports:
       - "6379:6379"