// <auto-generated />
using System;
using ConsolidadoDiario.ORM;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConsolidadoDiario.ORM.Migrations
{
    [DbContext(typeof(DefaultContext))]
    partial class DefaultContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConsolidadoDiario.Domain.Entities.ConsolidadoDiarioConta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataConsolidacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataUltimaAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NumeroAgencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroConta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SaldoConsolidado")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalCreditos")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalDebitos")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("ConsolidadoDiarioContas");
                });
#pragma warning restore 612, 618
        }
    }
}
