name: CI/CD Pipeline API controle-lancamentos

on:
  pull_request:
    branches: [ "master-controle-lancamentos" ]
    
env:
  DOTNET_VERSION: 9.0.x  # Consider using exact version like "9.0.100-preview.5"
  
jobs:
  ci:
    name: Integração Contínua
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v4
    
    # Add environment setup
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    # Add certificate trust for development (if needed)
    - name: Trust development certificate
      run: dotnet dev-certs https --trust
    
    # Restore with lock file
    - name: Restaurar dependências
      run: dotnet restore --use-lock-file
    
    # Build with warning as errors
    - name: Construir projeto
      run: dotnet build --no-restore -c Release --warnaserror
    
    # Test with coverage
    - name: Executar testes
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"
    
    # Optional: Publish test results
    - name: Publish Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: TestResults/